---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nio.homystack.com
  resources:
  - machines
  - nixbuilders
  - nixosconfigurations
  - nixstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nio.homystack.com
  resources:
  - machines/finalizers
  - nixbuilders/finalizers
  - nixosconfigurations/finalizers
  - nixstores/finalizers
  verbs:
  - update
- apiGroups:
  - nio.homystack.com
  resources:
  - machines/status
  - nixbuilders/status
  - nixosconfigurations/status
  - nixstores/status
  verbs:
  - get
  - patch
  - update
