apiVersion: nio.homystack.com/v1alpha1
kind: Machine
metadata:
  name: test
  namespace: default
spec:
  hostname: 198.51.100.10
  sshUser: kitsunoff
  sshKeySecretRef:
    name: ssh-private-key
    namespace: default
